### ISSUE TITLE
New DCPM hardware

### ISSUE THREAD

**Issue by MattTraina** [Altronic-LLC/Altronic-Public-Files#11]
Verify that the ports all work and can talk out the RS-485

**Comment by MattTraina** [comment]
@lm1099 I have uploaded the R2 schematic under the DCPM scanner repo.

**Comment by lm1099** [comment]
@MattTraina I am currently setting up the new hardware, and would like to test out the CIU, but I'm not sure how to connect it. Could you also send the schematic for the CIU?

**Comment by MattTraina** [comment]
@lm1099  I have uploaded the version of hardware you have here https://github.com/Altronic-LLC/NGI-5000-CIU/tree/main/Hardware

**Comment by lm1099** [comment]
@MattTraina It looks like the hub layout on the DCPM board that I have is slightly different than the layout depicted by the schematic in the DCPM scanner repo. Is the schematic in the repo the most current or has it been updated since this hardware was built?

**Comment by lm1099** [comment]
altronic@altronic:~ $ lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc2/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 480M
        |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 480M
        |__ Port 2: Dev 4, If 0, Class=Hub, Driver=hub/5p, 480M
            |__ Port 5: Dev 19, If 0, Class=Hub, Driver=hub/7p, 480M
                |__ Port 5: Dev 40, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 5: Dev 40, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 3: Dev 32, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 3: Dev 32, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 1: Dev 24, If 0, Class=Communications, Driver=cdc_ether, 480M
                |__ Port 1: Dev 24, If 1, Class=CDC Data, Driver=cdc_ether, 480M
                |__ Port 6: Dev 43, If 0, Class=Human Interface Device, Driver=usbhid, 480M
                |__ Port 4: Dev 36, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 4: Dev 36, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 2: Dev 28, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 2: Dev 28, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 7: Dev 45, If 0, Class=Human Interface Device, Driver=usbhid, 480M
            |__ Port 3: Dev 12, If 0, Class=Hub, Driver=hub/7p, 480M
                |__ Port 6: Dev 38, If 0, Class=Human Interface Device, Driver=usbhid, 480M
                |__ Port 4: Dev 30, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 4: Dev 30, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 2: Dev 22, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 2: Dev 22, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 7: Dev 42, If 0, Class=Human Interface Device, Driver=usbhid, 480M
                |__ Port 5: Dev 34, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 5: Dev 34, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 3: Dev 26, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 3: Dev 26, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 1: Dev 17, If 1, Class=CDC Data, Driver=cdc_ether, 480M
                |__ Port 1: Dev 17, If 0, Class=Communications, Driver=cdc_ether, 480M
            |__ Port 1: Dev 6, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 480M
            |__ Port 4: Dev 15, If 0, Class=Hub, Driver=hub/7p, 480M
                |__ Port 2: Dev 25, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 2: Dev 25, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 7: Dev 44, If 0, Class=Human Interface Device, Driver=usbhid, 480M
                |__ Port 5: Dev 37, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 5: Dev 37, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 3: Dev 29, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 3: Dev 29, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 1: Dev 21, If 0, Class=Communications, Driver=cdc_ether, 480M
                |__ Port 1: Dev 21, If 1, Class=CDC Data, Driver=cdc_ether, 480M
                |__ Port 6: Dev 41, If 0, Class=Human Interface Device, Driver=usbhid, 480M
                |__ Port 4: Dev 33, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 4: Dev 33, If 0, Class=Communications, Driver=xr_serial, 480M
            |__ Port 2: Dev 10, If 0, Class=Hub, Driver=hub/7p, 480M
                |__ Port 3: Dev 23, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 3: Dev 23, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 1: Dev 14, If 0, Class=Communications, Driver=cdc_ether, 480M
                |__ Port 1: Dev 14, If 1, Class=CDC Data, Driver=cdc_ether, 480M
                |__ Port 6: Dev 35, If 0, Class=Human Interface Device, Driver=usbhid, 480M
                |__ Port 4: Dev 27, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 4: Dev 27, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 2: Dev 18, If 1, Class=CDC Data, Driver=xr_serial, 480M
                |__ Port 2: Dev 18, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 7: Dev 39, If 0, Class=Human Interface Device, Driver=usbhid, 480M
                |__ Port 5: Dev 31, If 0, Class=Communications, Driver=xr_serial, 480M
                |__ Port 5: Dev 31, If 1, Class=CDC Data, Driver=xr_serial, 480M
        |__ Port 3: Dev 5, If 0, Class=Hub, Driver=hub/7p, 480M
            |__ Port 1: Dev 7, If 1, Class=CDC Data, Driver=cdc_ether, 480M
            |__ Port 1: Dev 7, If 0, Class=Communications, Driver=cdc_ether, 480M
            |__ Port 2: Dev 8, If 1, Class=CDC Data, Driver=xr_serial, 480M
            |__ Port 2: Dev 8, If 0, Class=Communications, Driver=xr_serial, 480M
            |__ Port 3: Dev 9, If 0, Class=Communications, Driver=xr_serial, 480M
            |__ Port 3: Dev 9, If 1, Class=CDC Data, Driver=xr_serial, 480M
            |__ Port 4: Dev 11, If 0, Class=Communications, Driver=xr_serial, 480M
            |__ Port 4: Dev 11, If 1, Class=CDC Data, Driver=xr_serial, 480M
            |__ Port 5: Dev 13, If 1, Class=CDC Data, Driver=xr_serial, 480M
            |__ Port 5: Dev 13, If 0, Class=Communications, Driver=xr_serial, 480M
            |__ Port 6: Dev 16, If 0, Class=Human Interface Device, Driver=usbhid, 480M
            |__ Port 7: Dev 20, If 0, Class=Human Interface Device, Driver=usbhid, 480M

**Comment by lm1099** [comment]
[NGI-5000_DCPM_topology.txt](https://github.com/Altronic-LLC/Altronic-Public-Files/files/14225108/NGI-5000_DCPM_topology.txt)

**Comment by MattTraina** [comment]
@lm1099 how is it going getting the hardware to talk all of the way to the RS -485?

**Comment by lm1099** [comment]
@MattTraina The hardware seems to be working all the way to the differential RS-485 output at the RJ45 jack. The waveform below shows an A character that I sent with a terminal emulator:


![Image](https://github.com/Altronic-LLC/Altronic-Public-Files/assets/50176812/d95cf1f0-1e8c-4bc6-8444-f02ccbf92502)

**Comment by MattTraina** [comment]
@lm1099 this is great news. What is your planned next step? My thought would be to get a CIU talking, then get the DCPM scanner working.

@Gary-Alt   FYI

**Comment by lm1099** [comment]
@MattTraina My plan is to test communication with the CIU using the DCPM scanner program. I am currently using a C program to set the configure the RS485 ports, but I would like to build that in to the scanner program

**Comment by MattTraina** [comment]
@lm1099  you can find the modbus list for the CIU here
https://altronic.netlify.app/

**Comment by lm1099** [comment]
@MattTraina That's helpful, thanks! Which version of the NGI-5000CIU DEV would it be in that list?

**Comment by MattTraina** [comment]
@lm1099  were you able to get the CIU talking?

**Comment by lm1099** [comment]
@MattTraina Yes, thanks to Aaron and Gary's help, the CIU seems to be working with the Altronic modbus tool.

**Comment by lm1099** [comment]
@MattTraina @Gary-Alt This is a capture of a modbus request from a test program I created in Go:



![Image](https://github.com/Altronic-LLC/Altronic-Public-Files/assets/50176812/aa8f533b-0aa8-40a9-883b-7a20309ca060)

**Comment by MattTraina** [comment]
notes 2-22-24 
Aaron sent instructions on programming CIU. Landon could program the CIU and make it respond to the DCPM scanner program. Landon still needs to test all 20 outputs. He has tested 8 so far

**Comment by MattTraina** [comment]
@lm1099 any update on this task? I believe this was the next focus area. 

Thanks,

**Comment by lm1099** [comment]
I tested all 20 outputs on the DCPM and found that they all worked nominally. However, the map that I created for ports J, K, L, M, N, O, R, and S didn't seem to align with the schematic. I adjusted the udev rules to match what was reported on my physical hardware, but it might be worth double-checking the schematic.

**Comment by MattTraina** [comment]
This has been verified and tested.
