### ISSUE TITLE
Dev rule naming for communication paths

### ISSUE THREAD

**Issue by MattTraina** [Altronic-LLC/Altronic-Public-Files#6]
Provide output name and path linkage to the port to landon

**Comment by lm1099** [comment]
@MattTraina Let me know when you have the port names and I can update the udev rules to match.

**Comment by MattTraina** [comment]
This links to Files#7 so reporting here and closing out

@lm1099 Attached is an excel sheet that has the path from the CM4 to the output. We want to use the OUTPUT_X nomenclature for the symbolic links


[CM4 to output connectors 2-1-2024.xlsx](https://github.com/Altronic-LLC/Altronic-Public-Files/files/14129983/CM4.to.output.connectors.2-1-2024.xlsx)
