### ISSUE TITLE
Update DCPm scanner for proper number of ports

### ISSUE THREAD

**Issue by MattTraina** [Altronic-LLC/Altronic-Public-Files#8]
Using the system config, translate the number of outputs there are to how many ports the DCPM needs to scan. For example if there are only 4 CIUs then it will only need to scan through the first four ports and then start over.

**Comment by MattTraina** [comment]
notes 2-22-24 First step is make the scanner program that will scan up to 20 CIUs 40 nodes. Make a variable in the scanner that we can enter and test a number of CIUs.

**Comment by lm1099** [comment]
@MattTraina I've created a test program that can be used to scan 40 nodes across 20 CIUs on the new DCPM hardware. The program can be installed using the package in the Github link, which will also install the necessary udev rules. I'll email Nick with instructions for running the program as well.

https://github.com/Matt-Traina/CM4_Core/blob/main/packages/NGI-5000_DCPM/dcpm_hw_check/releases/dcpm-hw-check_0.01.0-1_arm64.deb

**Comment by MattTraina** [comment]
@lm1099 that is fantastic news. Thanks for letting me know.

**Comment by MattTraina** [comment]
Aaron checked these and it could see node 1 and 2. Scanning through all of them. A list of all devices and nodes. Using messages for specific devices, instead of looking at the config file specifically. Look at the messages that should be sent and determine that it's there to open up communication. 
Any ones that are not there, it will get a timeout. 
Every time new communication is established it will have to reach out and ask it if it's there. 
If there is no response, it will trigger a flag and not continue to try and talk to it.

**Comment by MattTraina** [comment]
This is working, and makes non-responsive ports inactive. Moving to done
